"""
Create minimal valid LSTM artifacts (model.keras + scaler.json + meta.json) per symbol
when real trained weights are missing — enables Phase-1 audits (load + inference) on a fresh zip.

Not for live alpha: run scripts/train_multi_coin.py for production-quality weights.
Set ML_BOOTSTRAP_STUB=false to skip.
"""
from __future__ import annotations

import json
import os
from pathlib import Path
from typing import List, Tuple

from src.core.symbols import parse_supported_trading_symbols
from src.ml.feature_columns import FEATURE_COLUMNS_PRODUCTION


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _stub_needed_for_dir(model_dir: Path) -> bool:
    from src.ml.model_verify import check_model_artifacts

    return not check_model_artifacts(model_dir).get("all_present", False)


def write_stub_artifacts(
    out_dir: Path,
    *,
    symbol: str,
    timeframe: str,
    lookback: int,
    force: bool = False,
) -> bool:
    """Return True if files were written."""
    out_dir = Path(out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    if not force and not _stub_needed_for_dir(out_dir):
        return False

    import numpy as np
    import tensorflow as tf

    from src.ml.model_builder import build_production_lstm

    n_features = len(FEATURE_COLUMNS_PRODUCTION)
    model = build_production_lstm(lookback, n_features)
    model.save(out_dir / "model.keras")

    mean = np.zeros(n_features, dtype=np.float64)
    scale = np.ones(n_features, dtype=np.float64)
    scaler = {"mean": mean.tolist(), "scale": scale.tolist()}
    (out_dir / "scaler.json").write_text(json.dumps(scaler, indent=2))

    meta = {
        "lookback": lookback,
        "n_features": n_features,
        "feature_columns": list(FEATURE_COLUMNS_PRODUCTION),
        "symbol": symbol,
        "interval": timeframe,
        "stub": True,
        "note": "Generated by bootstrap_stub_models; replace via train_multi_coin.py for real ML.",
    }
    (out_dir / "meta.json").write_text(json.dumps(meta, indent=2))
    return True


def ensure_stub_models(
    *,
    symbols: List[str] | None = None,
    timeframe: str | None = None,
    lookback: int | None = None,
    force: bool = False,
) -> Tuple[int, List[str]]:
    """
    Ensure models/<SYMBOL>_<timeframe>/ has full artifacts for each symbol.
    Returns (written_count, list of paths touched).
    """
    root = _repo_root()
    tf_ = timeframe or os.getenv("TRADE_TIMEFRAME", "5m").strip()
    lb = lookback if lookback is not None else int(os.getenv("ML_LOOKBACK", "50"))
    syms = list(symbols) if symbols else list(parse_supported_trading_symbols())

    written = 0
    paths: List[str] = []
    for sym in syms:
        sym = sym.upper().strip()
        key = f"{sym}_{tf_}"
        out = root / "models" / key
        if write_stub_artifacts(
            out, symbol=sym, timeframe=tf_, lookback=lb, force=force
        ):
            written += 1
            paths.append(str(out))
    return written, paths


def bootstrap_if_enabled() -> None:
    """Called from app startup when ML_BOOTSTRAP_STUB is true (default)."""
    if os.getenv("ML_BOOTSTRAP_STUB", "true").strip().lower() not in (
        "1",
        "true",
        "yes",
    ):
        return
    if os.getenv("ML_ENABLED", "true").strip().lower() in ("0", "false", "no"):
        return

    from src.core.config import get_settings

    s = get_settings()
    if not getattr(s, "ml_enabled", False):
        return

    syms = list(getattr(s, "supported_trading_symbols", ()) or parse_supported_trading_symbols())
    tf_ = getattr(s, "trade_timeframe", "5m")
    lb = int(getattr(s, "ml_lookback", 50) or 50)

    any_missing = False
    root = _repo_root()
    for sym in syms:
        out = root / "models" / f"{sym.upper().strip()}_{tf_}"
        if _stub_needed_for_dir(out):
            any_missing = True
            break

    if not any_missing:
        return

    from src.core.ml_runtime_state import get_ml_state, set_model_error

    try:
        import tensorflow  # noqa: F401
    except ImportError as e:
        msg = (
            "TensorFlow is not installed — stub models cannot be created and inference will not run. "
            "Use Python 3.11 or 3.12, then: pip install -r requirements.txt"
        )
        set_model_error(f"{msg} (import error: {e})")
        print(f"[STARTUP][ML][ERROR] {get_ml_state().get('last_error')}")
        return

    try:
        n, paths = ensure_stub_models(symbols=syms, timeframe=tf_, lookback=lb, force=False)
        print(
            f"[STARTUP][ML] ML_BOOTSTRAP_STUB: wrote {n} model dir(s): {paths or '(none new)'}",
        )
    except Exception as exc:
        set_model_error(f"stub bootstrap failed: {exc}")
        print(f"[STARTUP][ML][ERROR] stub bootstrap failed: {exc}")
